
services:
  plexanisync:
    container_name: Plexanisync
    image: 'ghcr.io/rickdb/plexanisync:latest'
    restart: unless-stopped
    environment:
      - PLEX_SECTION=Anime-Shows|Anime-Movies
      - PLEX_URL=http://192.168.1.24:32400
      - PLEX_TOKEN=NweK8wg1zBJg2rBozTR1
      - ANI_USERNAME=Virmin8
      - ANI_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQwMzBmNTM5Y2QzNWZjYWZjMGIwNjA0NTU2OTVjNWIzMTU2YmM2ZmViYTRhNGQwMTc4MjgzZDJkYzUyNjQ2ZDI5YjIwNmRmMWYzMDA3NTc5In0.eyJhdWQiOiIxNTQ5IiwianRpIjoiNDAzMGY1MzljZDM1ZmNhZmMwYjA2MDQ1NTY5NWM1YjMxNTZiYzZmZWJhNGE0ZDAxNzgyODNkMmRjNTI2NDZkMjliMjA2ZGYxZjMwMDc1NzkiLCJpYXQiOjE3NDI0NjY5NTMsIm5iZiI6MTc0MjQ2Njk1MywiZXhwIjoxNzc0MDAyOTUzLCJzdWIiOiIxNTMxNTMiLCJzY29wZXMiOltdfQ.DhAxsr5bfDz30XBLElQlX4OzNenyQW6syW2eGSe0B_U4_b9coNebLNLU9uPuhqoi_tK7dPXnwCAIx82hoxH2sUVzfhBQOU9bWwXUzF65ycAx6nAxtQp9vF-qdRLPZZ-ZvdnHhNvLMfDOPmIzXT5vdTX4qBjrqvepaydnXwy2XExzlcig4IIM0GQRmp0WY4b8wk9TRtho6ykK0GoculDFLFvhO75woVScewxlnnpH8vH9kNWVb3Tr_HnphhPs0FvInLb3032bIpi4Nyaq2rm1pHzpTRqKMQR16GDJVh57DlZftRCCKNWDhtQyggF-a4vn2D61gwMYV8tHFxRePOg-BQYz4x-eekZrtIGNPtw_zJLIl4K0gdlM42jKImh9H3aAxOufGdVhrFnQ8RYn331CuIMD9ussjuCO80WJJUtfKsD33NW4dUknH_TQczPPW-BTdv4yoeuUA6_YEC_bh_zUBGhH0JbZTX6tO4NKaR5iuOP_7RJ_dvUahGzEuepSZxTsnxMsecvpO9-9IOb9SkjP5i9Q5sRLiZVSfu33c-bMlsZKzfNfEO1v6yHxUBw8YmpsEozHnVr-b07T3UvbBl20A30iDKWF-ZGdaDS4cwbUKx3B3yq_zcjGxHfht7NWcYvVbWIKyDr8sz83WDMMPhTFa_KSX-a6ob3U2wcuB6WoxCo
      - INTERVAL=3600
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/srv/config/PlexAniSync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml'