
services:
  plexanisync:
    container_name: Plexanisync
    image: 'ghcr.io/rickdb/plexanisync:latest'
    restart: unless-stopped
    environment:
      - PLEX_SECTION=Anime-Shows|Anime-Movies
      - PLEX_URL=http://192.168.1.24:32400
      - PLEX_TOKEN=${PLEX_TOKEN}
      - ANI_USERNAME=Virmin8
      - ANI_TOKEN=${ANI_TOKEN}
      - INTERVAL=3600
    env_file:
      - .env
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/srv/config/PlexAniSync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml'