services:
  overseerr:
    image: sctx/overseerr:develop
    container_name: Overseerr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=web, websecure"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.virmin8.uk`)"
      - "traefik.http.routers.overseerr.tls=true"

    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/config/Overseer/:/app/config
    restart: unless-stopped
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
