services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: Cloudflared
    command: ${COMMAND}
    env_file:
      - .env
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
