services:
  tasmoadmin:
    container_name: TasmoAdmin
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasmoadmin.entrypoints=web, websecure"
      - "traefik.http.routers.tasmoadmin.rule=Host(`tasmoadmin.virmin8.uk`)"
      - "traefik.http.routers.tasmoadmin.tls=true"
      - "traefik.http.routers.tasmoadmin.middlewares=auth@file"
    volumes:
      - /srv/config/TasmataAdmin:/data
    restart: unless-stopped
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
