services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: Syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-49c13bd6-d6eb-4d54-b023-8b27d14e1d1a/Backup:/var/syncthing
    restart: unless-stopped
    network_mode: host