services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: FlareSolverr	
    restart: unless-stopped 
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true