---
services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: Kometa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - /srv/config/Kometa/config:/config
    restart: unless-stopped
