services:
  sonarr:
    container_name: Maintainerr
    image: jorenn92/maintainerr:develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintainerr.entrypoints=web, websecure"
      - "traefik.http.routers.maintainerr.rule=Host(`maintainerr.virmin8.uk`)"
      - "traefik.http.routers.maintainerr.tls=true"
     # - "traefik.http.routers.maintainerr.middlewares=auth@file"
      
    user: 1000:1000
    volumes:
      - /srv/config/Maintainerr:/opt/data
    restart: unless-stopped
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
